name: main
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install Dependencies
        run: |
          uv python install 3.11
          uv sync
      - name: Build docs
        run: |
          cp sax_workshop.ipynb ./docs
          cd docs && ../.venv/bin/jb build .
          touch docs/_build/html/.nojekyll
      - name: Store artifacts
        uses: actions/upload-artifact@master
        with:
          name: docs
          path: docs/_build/html

  pages:
    runs-on: ubuntu-latest
    needs:
      - docs
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download 'docs' artifact
        uses: actions/download-artifact@master
        with:
          name: docs
          path: docs/_build/html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          branch: pages
          folder: docs/_build/html
